<?php
/**
 * Waves Platform - Main Configuration Bootstrap
 * This file is auto-generated by the installer. Do not edit manually.
 */

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'u983353360_ar');
define('DB_USER', 'u983353360_ar');
define('DB_PASS', 'yYu2A5s/');
define('DB_CHARSET', 'utf8mb4');

// App Configuration
define('APP_VERSION', '1.0.0');
define('UPLOAD_DIR', __DIR__ . '/uploads/');

// Error Reporting
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// Timezone
date_default_timezone_set('Asia/Riyadh');

// Load core includes
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/csrf.php';
require_once __DIR__ . '/includes/lang.php';
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/email.php';

// Start session
initSession();

// Database Connection
try {
    $pdo = new PDO(
        "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=" . DB_CHARSET,
        DB_USER,
        DB_PASS,
        [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false
        ]
    );
} catch (PDOException $e) {
    die('Database connection error / خطأ في الاتصال بقاعدة البيانات');
}
