<?php
/**
 * Waves Platform - Multi-Step Installation Wizard
 * Creates database tables, admin account, and system configuration
 */
session_start();

$step = (int)($_GET['step'] ?? ($_POST['step'] ?? 1));
$errors = [];
$success = false;

// Already installed check
if (file_exists(__DIR__ . '/installed.lock') && $step < 4) {
    $step = 0; // Show already-installed message
}

// --- Handle POST actions ---
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    // Step 2: Test DB + Create Tables
    if ($step === 2) {
        $dbHost = trim($_POST['db_host'] ?? 'localhost');
        $dbName = trim($_POST['db_name'] ?? '');
        $dbUser = trim($_POST['db_user'] ?? '');
        $dbPass = $_POST['db_pass'] ?? '';

        try {
            $pdo = new PDO("mysql:host={$dbHost};dbname={$dbName};charset=utf8mb4", $dbUser, $dbPass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            // Store in session for next step
            $_SESSION['install_db'] = compact('dbHost', 'dbName', 'dbUser', 'dbPass');

            // Create all tables
            $tables = getTableSQL();
            foreach ($tables as $sql) {
                $pdo->exec($sql);
            }

            // Insert default settings
            $defaults = [
                'site_title' => 'Waves Platform',
                'default_language' => 'ar',
                'timezone' => 'Asia/Riyadh',
                'max_upload_size' => '52428800',
                'allowed_extensions' => 'jpg,jpeg,png,gif,webp,pdf,doc,docx,xls,xlsx,ppt,pptx,zip,rar,7z,mp4,mov,avi,psd,ai,svg,txt,csv',
                'smtp_host' => '',
                'smtp_port' => '587',
                'smtp_username' => '',
                'smtp_password' => '',
                'smtp_encryption' => 'tls',
                'smtp_from_email' => '',
                'smtp_from_name' => 'Waves Platform',
                'project_title' => 'Waves × Details Project',
                'project_description' => '',
            ];
            $stmtIns = $pdo->prepare("INSERT IGNORE INTO settings (setting_key, setting_value) VALUES (?, ?)");
            foreach ($defaults as $k => $v) {
                $stmtIns->execute([$k, $v]);
            }

            $step = 3; // Move to admin creation step

        } catch (PDOException $e) {
            $errors[] = 'Database error: ' . $e->getMessage();
            $step = 2;
        }
    }

    // Step 3: Create Admin Account
    if ($step === 3 && isset($_POST['admin_name'])) {
        $adminName = trim($_POST['admin_name'] ?? '');
        $adminEmail = trim($_POST['admin_email'] ?? '');
        $adminPass = $_POST['admin_password'] ?? '';

        if (empty($adminName) || empty($adminEmail) || strlen($adminPass) < 6) {
            $errors[] = 'All fields are required. Password must be at least 6 characters.';
            $step = 3;
        } else {
            $db = $_SESSION['install_db'] ?? null;
            if (!$db) { $errors[] = 'Session expired. Please restart.'; $step = 1; }
            else {
                try {
                    $pdo = new PDO("mysql:host={$db['dbHost']};dbname={$db['dbName']};charset=utf8mb4",
                        $db['dbUser'], $db['dbPass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

                    $hashedPass = password_hash($adminPass, PASSWORD_DEFAULT);
                    $stmt = $pdo->prepare("INSERT INTO users (name, email, password, role, company, is_active) VALUES (?, ?, ?, 'admin', 'Waves', 1)");
                    $stmt->execute([$adminName, $adminEmail, $hashedPass]);

                    // Write config.php
                    $configContent = '<?php' . "\n";
                    $configContent .= "/**\n * Waves Platform - Main Configuration\n * Auto-generated by installer on " . date('Y-m-d H:i:s') . "\n */\n\n";
                    $configContent .= "define('DB_HOST', " . var_export($db['dbHost'], true) . ");\n";
                    $configContent .= "define('DB_NAME', " . var_export($db['dbName'], true) . ");\n";
                    $configContent .= "define('DB_USER', " . var_export($db['dbUser'], true) . ");\n";
                    $configContent .= "define('DB_PASS', " . var_export($db['dbPass'], true) . ");\n";
                    $configContent .= "define('DB_CHARSET', 'utf8mb4');\n\n";
                    $configContent .= "define('APP_VERSION', '1.0.0');\n";
                    $configContent .= "define('UPLOAD_DIR', __DIR__ . '/uploads/');\n\n";
                    $configContent .= "error_reporting(E_ALL);\nini_set('display_errors', 0);\nini_set('log_errors', 1);\n\n";
                    $configContent .= "date_default_timezone_set('Asia/Riyadh');\n\n";
                    $configContent .= "require_once __DIR__ . '/includes/auth.php';\n";
                    $configContent .= "require_once __DIR__ . '/includes/csrf.php';\n";
                    $configContent .= "require_once __DIR__ . '/includes/lang.php';\n";
                    $configContent .= "require_once __DIR__ . '/includes/functions.php';\n";
                    $configContent .= "require_once __DIR__ . '/includes/email.php';\n\n";
                    $configContent .= "initSession();\n\n";
                    $configContent .= "try {\n";
                    $configContent .= "    \$pdo = new PDO(\n";
                    $configContent .= "        'mysql:host=' . DB_HOST . ';dbname=' . DB_NAME . ';charset=' . DB_CHARSET,\n";
                    $configContent .= "        DB_USER, DB_PASS,\n";
                    $configContent .= "        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_EMULATE_PREPARES => false]\n";
                    $configContent .= "    );\n";
                    $configContent .= "} catch (PDOException \$e) {\n";
                    $configContent .= "    die('Database connection error');\n";
                    $configContent .= "}\n";

                    file_put_contents(__DIR__ . '/config.php', $configContent);

                    // Create upload directories
                    foreach (['uploads', 'uploads/attachments', 'uploads/avatars'] as $dir) {
                        if (!is_dir(__DIR__ . '/' . $dir)) mkdir(__DIR__ . '/' . $dir, 0755, true);
                    }

                    // Lock file
                    file_put_contents(__DIR__ . '/installed.lock', json_encode([
                        'installed_at' => date('Y-m-d H:i:s'),
                        'admin_email' => $adminEmail,
                        'version' => '1.0.0'
                    ]));

                    $_SESSION['install_admin_email'] = $adminEmail;
                    unset($_SESSION['install_db']);

                    $step = 4; // Success
                    $success = true;

                } catch (PDOException $e) {
                    $errors[] = 'Error: ' . $e->getMessage();
                    $step = 3;
                }
            }
        }
    }
}

function esc($s) { return htmlspecialchars($s ?? '', ENT_QUOTES, 'UTF-8'); }

function getTableSQL() {
    return [
        "CREATE TABLE IF NOT EXISTS `users` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `name` VARCHAR(100) NOT NULL,
            `email` VARCHAR(150) NOT NULL UNIQUE,
            `password` VARCHAR(255) NOT NULL,
            `phone` VARCHAR(20) DEFAULT NULL,
            `role` ENUM('admin','project_manager','client') NOT NULL DEFAULT 'client',
            `company` VARCHAR(150) DEFAULT NULL,
            `avatar` VARCHAR(255) DEFAULT NULL,
            `is_active` TINYINT(1) DEFAULT 1,
            `last_login` DATETIME DEFAULT NULL,
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
            `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

        "CREATE TABLE IF NOT EXISTS `tasks` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `title` VARCHAR(255) NOT NULL,
            `description` TEXT DEFAULT NULL,
            `category` VARCHAR(100) DEFAULT NULL,
            `status` ENUM('new','in_progress','delivered','pending_review','needs_revision','completed','archived') DEFAULT 'new',
            `priority` ENUM('low','medium','high','urgent') DEFAULT 'medium',
            `progress` INT DEFAULT 0,
            `start_date` DATE DEFAULT NULL,
            `due_date` DATE DEFAULT NULL,
            `delivery_date` DATETIME DEFAULT NULL,
            `completed_date` DATETIME DEFAULT NULL,
            `created_by` INT NOT NULL,
            `assigned_to` INT DEFAULT NULL,
            `internal_notes` TEXT DEFAULT NULL,
            `client_notes` TEXT DEFAULT NULL,
            `revision_count` INT DEFAULT 0,
            `estimated_hours` DECIMAL(6,2) DEFAULT NULL,
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
            `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE CASCADE,
            FOREIGN KEY (`assigned_to`) REFERENCES `users`(`id`) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

        "CREATE TABLE IF NOT EXISTS `task_comments` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `task_id` INT NOT NULL,
            `user_id` INT NOT NULL,
            `comment` TEXT NOT NULL,
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE CASCADE,
            FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

        "CREATE TABLE IF NOT EXISTS `task_attachments` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `task_id` INT NOT NULL,
            `comment_id` INT DEFAULT NULL,
            `user_id` INT NOT NULL,
            `file_name` VARCHAR(255) NOT NULL,
            `original_name` VARCHAR(255) NOT NULL,
            `file_size` BIGINT DEFAULT 0,
            `file_type` VARCHAR(100) DEFAULT NULL,
            `version` INT DEFAULT 1,
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE CASCADE,
            FOREIGN KEY (`comment_id`) REFERENCES `task_comments`(`id`) ON DELETE SET NULL,
            FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

        "CREATE TABLE IF NOT EXISTS `notifications` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `user_id` INT NOT NULL,
            `title` VARCHAR(255) NOT NULL,
            `message` TEXT DEFAULT NULL,
            `link` VARCHAR(255) DEFAULT NULL,
            `is_read` TINYINT(1) DEFAULT 0,
            `type` VARCHAR(50) DEFAULT 'info',
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

        "CREATE TABLE IF NOT EXISTS `activity_log` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `user_id` INT DEFAULT NULL,
            `action` VARCHAR(100) NOT NULL,
            `description` TEXT DEFAULT NULL,
            `entity_type` VARCHAR(50) DEFAULT NULL,
            `entity_id` INT DEFAULT NULL,
            `ip_address` VARCHAR(45) DEFAULT NULL,
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

        "CREATE TABLE IF NOT EXISTS `settings` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `setting_key` VARCHAR(100) NOT NULL UNIQUE,
            `setting_value` TEXT DEFAULT NULL,
            `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

        "CREATE TABLE IF NOT EXISTS `password_resets` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `email` VARCHAR(150) NOT NULL,
            `token` VARCHAR(255) NOT NULL,
            `expires_at` DATETIME NOT NULL,
            `used` TINYINT(1) DEFAULT 0,
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

        "CREATE TABLE IF NOT EXISTS `task_status_history` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `task_id` INT NOT NULL,
            `user_id` INT DEFAULT NULL,
            `old_status` VARCHAR(50) DEFAULT NULL,
            `new_status` VARCHAR(50) NOT NULL,
            `comment` TEXT DEFAULT NULL,
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON DELETE CASCADE,
            FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",

        "CREATE TABLE IF NOT EXISTS `email_log` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `recipient` VARCHAR(150) NOT NULL,
            `subject` VARCHAR(255) DEFAULT NULL,
            `status` VARCHAR(20) DEFAULT 'pending',
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ];
}
?>
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Waves - Installation Wizard</title>
    <link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@300;400;500;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        *{margin:0;padding:0;box-sizing:border-box}
        body{font-family:'Tajawal',sans-serif;background:linear-gradient(135deg,#0f172a,#1e293b,#0f172a);min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}
        .card{background:rgba(255,255,255,.05);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,.1);border-radius:24px;padding:48px;width:100%;max-width:580px;box-shadow:0 25px 60px rgba(0,0,0,.35)}
        .logo{text-align:center;margin-bottom:32px}
        .logo h1{font-size:34px;font-weight:800;background:linear-gradient(135deg,#6366f1,#8b5cf6,#a78bfa);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:6px}
        .logo p{color:#94a3b8;font-size:15px}

        /* Steps indicator */
        .steps{display:flex;justify-content:center;gap:8px;margin-bottom:32px}
        .step-dot{width:40px;height:5px;border-radius:3px;background:rgba(255,255,255,.08);transition:.3s}
        .step-dot.done{background:#22c55e}
        .step-dot.active{background:linear-gradient(90deg,#6366f1,#a78bfa);width:60px}

        .step-label{text-align:center;color:#94a3b8;font-size:14px;margin-bottom:24px;font-weight:500}
        .step-label span{color:#a78bfa;font-weight:700}

        .form-group{margin-bottom:18px}
        .form-group label{display:block;color:#cbd5e1;font-size:13px;font-weight:600;margin-bottom:7px}
        .form-group input,.form-group select{width:100%;padding:13px 16px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:10px;color:#f1f5f9;font-family:'Tajawal',sans-serif;font-size:14px;outline:none;transition:.3s}
        .form-group input:focus{border-color:#6366f1;box-shadow:0 0 0 3px rgba(99,102,241,.18)}
        .form-group input::placeholder{color:#64748b}
        .form-row{display:grid;grid-template-columns:1fr 1fr;gap:14px}

        .btn{width:100%;padding:15px;background:linear-gradient(135deg,#6366f1,#7c3aed);color:#fff;border:none;border-radius:12px;font-family:'Tajawal',sans-serif;font-size:16px;font-weight:700;cursor:pointer;transition:.3s;margin-top:8px;display:flex;align-items:center;justify-content:center;gap:8px}
        .btn:hover{transform:translateY(-2px);box-shadow:0 10px 30px rgba(99,102,241,.35)}
        .btn-outline{background:transparent;border:1px solid rgba(255,255,255,.15);color:#94a3b8;box-shadow:none}
        .btn-outline:hover{border-color:#6366f1;color:#a78bfa;transform:none;box-shadow:none}
        a.btn{text-decoration:none;text-align:center}

        .alert{padding:13px 16px;border-radius:10px;margin-bottom:18px;font-size:13px;display:flex;align-items:center;gap:8px}
        .alert-danger{background:rgba(239,68,68,.12);border:1px solid rgba(239,68,68,.25);color:#fca5a5}
        .alert-success{background:rgba(34,197,94,.12);border:1px solid rgba(34,197,94,.25);color:#86efac}
        .alert-warning{background:rgba(245,158,11,.12);border:1px solid rgba(245,158,11,.25);color:#fcd34d}

        .success-icon{text-align:center;margin-bottom:20px}
        .success-icon i{font-size:56px;color:#22c55e}

        .info-box{background:rgba(99,102,241,.08);border:1px solid rgba(99,102,241,.18);border-radius:12px;padding:16px;margin:20px 0}
        .info-box p{color:#c4b5fd;font-size:13px;margin-bottom:5px;display:flex;align-items:center;gap:6px}
        .info-box p:last-child{margin-bottom:0}
        .info-box strong{color:#e0e7ff}

        .check-list{list-style:none;margin:16px 0}
        .check-list li{display:flex;align-items:center;gap:8px;padding:8px 0;color:#94a3b8;font-size:13px}
        .check-list li i.fa-check-circle{color:#22c55e}
        .check-list li i.fa-times-circle{color:#ef4444}

        @media(max-width:480px){.card{padding:28px 20px}.form-row{grid-template-columns:1fr}}
    </style>
</head>
<body>
<div class="card">
    <div class="logo">
        <div style="display:flex;align-items:center;justify-content:center;gap:16px;margin-bottom:12px">
            <img src="assets/img/waves-logo.png" alt="Waves" style="height:44px;filter:brightness(0) invert(1);opacity:.9">
            <span style="color:rgba(255,255,255,.2);font-size:18px">&times;</span>
            <img src="assets/img/details-logo.png" alt="Details" style="height:44px;filter:brightness(0) invert(1);opacity:.9">
        </div>
        <p>Project Tracking Platform / منصة متابعة المشروع</p>
    </div>

    <?php if ($step === 0): // Already installed ?>
        <div class="alert alert-warning"><i class="fas fa-info-circle"></i> Platform is already installed. Delete <strong>installed.lock</strong> to reinstall.</div>
        <a href="login.php" class="btn"><i class="fas fa-sign-in-alt"></i> Go to Login</a>

    <?php elseif ($step === 1): // Welcome + System Check ?>
        <div class="steps"><div class="step-dot active"></div><div class="step-dot"></div><div class="step-dot"></div></div>
        <div class="step-label">Step <span>1/3</span> — System Check</div>

        <?php
        $phpOk = version_compare(PHP_VERSION, '7.4', '>=');
        $pdoOk = extension_loaded('pdo_mysql');
        $mbOk = extension_loaded('mbstring');
        $jsonOk = extension_loaded('json');
        $writableConf = is_writable(__DIR__);
        $writableUpl = is_dir(__DIR__ . '/uploads') ? is_writable(__DIR__ . '/uploads') : is_writable(__DIR__);
        $allOk = $phpOk && $pdoOk && $mbOk && $jsonOk && $writableConf;
        ?>
        <ul class="check-list">
            <li><i class="fas <?= $phpOk ? 'fa-check-circle' : 'fa-times-circle' ?>"></i> PHP <?= PHP_VERSION ?> (7.4+ required)</li>
            <li><i class="fas <?= $pdoOk ? 'fa-check-circle' : 'fa-times-circle' ?>"></i> PDO MySQL Extension</li>
            <li><i class="fas <?= $mbOk ? 'fa-check-circle' : 'fa-times-circle' ?>"></i> Mbstring Extension</li>
            <li><i class="fas <?= $jsonOk ? 'fa-check-circle' : 'fa-times-circle' ?>"></i> JSON Extension</li>
            <li><i class="fas <?= $writableConf ? 'fa-check-circle' : 'fa-times-circle' ?>"></i> Directory writable</li>
        </ul>

        <?php if ($allOk): ?>
            <a href="install.php?step=2" class="btn"><i class="fas fa-arrow-left"></i> Next: Database Setup</a>
        <?php else: ?>
            <div class="alert alert-danger"><i class="fas fa-exclamation-triangle"></i> Please fix the issues above before continuing.</div>
        <?php endif; ?>

    <?php elseif ($step === 2): // Database Setup ?>
        <div class="steps"><div class="step-dot done"></div><div class="step-dot active"></div><div class="step-dot"></div></div>
        <div class="step-label">Step <span>2/3</span> — Database Connection</div>

        <?php foreach ($errors as $err): ?><div class="alert alert-danger"><i class="fas fa-times-circle"></i> <?= esc($err) ?></div><?php endforeach; ?>

        <form method="POST">
            <input type="hidden" name="step" value="2">
            <div class="form-group">
                <label>Database Host</label>
                <input type="text" name="db_host" value="localhost" required>
            </div>
            <div class="form-group">
                <label>Database Name</label>
                <input type="text" name="db_name" value="u983353360_ar" required placeholder="Enter database name">
            </div>
            <div class="form-row">
                <div class="form-group">
                    <label>Username</label>
                    <input type="text" name="db_user" value="u983353360_ar" required>
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input type="password" name="db_pass" value="yYu2A5s/" required>
                </div>
            </div>
            <button type="submit" class="btn"><i class="fas fa-database"></i> Connect & Create Tables</button>
            <a href="install.php?step=1" class="btn btn-outline" style="margin-top:8px"><i class="fas fa-arrow-right"></i> Back</a>
        </form>

    <?php elseif ($step === 3): // Admin Account ?>
        <div class="steps"><div class="step-dot done"></div><div class="step-dot done"></div><div class="step-dot active"></div></div>
        <div class="step-label">Step <span>3/3</span> — Admin Account</div>

        <div class="alert alert-success"><i class="fas fa-check-circle"></i> Database connected and tables created successfully!</div>
        <?php foreach ($errors as $err): ?><div class="alert alert-danger"><i class="fas fa-times-circle"></i> <?= esc($err) ?></div><?php endforeach; ?>

        <form method="POST">
            <input type="hidden" name="step" value="3">
            <div class="form-group">
                <label>Admin Name</label>
                <input type="text" name="admin_name" value="<?= esc($_POST['admin_name'] ?? 'System Admin') ?>" required placeholder="Full name">
            </div>
            <div class="form-group">
                <label>Email Address</label>
                <input type="email" name="admin_email" value="<?= esc($_POST['admin_email'] ?? 'admin@waves.sa') ?>" required placeholder="admin@example.com">
            </div>
            <div class="form-group">
                <label>Password (min 6 characters)</label>
                <input type="password" name="admin_password" required minlength="6" placeholder="Enter a strong password">
            </div>
            <button type="submit" class="btn"><i class="fas fa-rocket"></i> Complete Installation</button>
        </form>

    <?php elseif ($step === 4): // Success ?>
        <div class="steps"><div class="step-dot done"></div><div class="step-dot done"></div><div class="step-dot done"></div></div>
        <div class="success-icon"><i class="fas fa-check-circle"></i></div>
        <div class="alert alert-success" style="text-align:center;justify-content:center">
            <strong>Installation Complete!</strong>
        </div>
        <div class="info-box">
            <p><strong>Login credentials:</strong></p>
            <p><i class="fas fa-envelope"></i> Email: <strong><?= esc($_SESSION['install_admin_email'] ?? '') ?></strong></p>
            <p><i class="fas fa-lock"></i> Password: <strong>(the one you just set)</strong></p>
        </div>
        <div class="alert alert-warning"><i class="fas fa-shield-alt"></i> For security, delete <strong>install.php</strong> after logging in.</div>
        <a href="login.php" class="btn"><i class="fas fa-sign-in-alt"></i> Go to Login</a>
    <?php endif; ?>
</div>
</body>
</html>
